name: PR
on: [push]
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.20.2'
permissions:
  contents: read

jobs:
  # Runs before all other jobs
  # builds the minikube binaries
  build_minikube:
    runs-on: ubuntu-20.04
    steps:
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Download Dependencies
        run: sudo -E go run .
